version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: learn-loop-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: learn-loop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - learn-loop-network

volumes:
  postgres_data:

networks:
  learn-loop-network:
    driver: bridge